- Makefile
- runner/src/main.rs
- runner/src/scenario/ipfs_block_fetch.rs
- runner/src/simulate.rs
Prior to this change the simulate command assumed the peer RPC address based on the peer index. Now with this change a JSON encoding of peers and their address must be specified. This enables the simulate command to work well with the operator.
> fix: update simulate cmd to take assembled peers info

- Cargo.lock
- operator/Cargo.toml
- operator/src/network/controller.rs
- operator/src/network/mod.rs
- operator/src/network/stub.rs
- operator/src/network/testdata/bootstrap_job_two_peers
- operator/src/network/testdata/default_stubs/cas_ipfs_service
- operator/src/network/testdata/default_stubs/cas_ipfs_stateful_set
- operator/src/network/testdata/default_stubs/cas_postgres_service
- operator/src/network/testdata/default_stubs/cas_postgres_stateful_set
- operator/src/network/testdata/default_stubs/cas_service
- operator/src/network/testdata/default_stubs/cas_stateful_set
- operator/src/network/testdata/default_stubs/ceramic_admin_secret
- operator/src/network/testdata/default_stubs/ceramic_init_configmap
- operator/src/network/testdata/default_stubs/ceramic_service
- operator/src/network/testdata/default_stubs/ceramic_stateful_set
- operator/src/network/testdata/default_stubs/ganache_service
- operator/src/network/testdata/default_stubs/ganache_stateful_set
- operator/src/network/testdata/default_stubs/keramik_peers_configmap
- operator/src/network/testdata/default_stubs/namespace
- operator/src/network/testdata/default_stubs/postgres_auth_secret
- operator/src/network/testdata/default_stubs/status
- operator/src/network/utils.rs
These tests follow a basic pattern. First the controller is basically responsible for making API calls to the k8s API. So to test it we use a combination of mocks, stubs and expect_test to build a basic test framework. The mock/stubs capture the requests made to the API and return responses. The `expect_test` crate is used to assert the correctness of the requests while making it easy to update the tests when the code itself is changed. Additionally an `ExpectPatch` concept is added that allows for  patching the default stubs instead of reproducing their entire contents for each test.
> fix: add tests for operator

- operator/src/network/cas.rs
- operator/src/network/ceramic.rs
- operator/src/network/controller.rs
- operator/src/network/testdata/default_stubs/ceramic_stateful_set
- operator/src/network/utils.rs
With this change CAS (cas, cas_ipfs, ganache and postgres) along with Ceramic nodes (both js and ipfs nodes) can have their resource limits configured.
Currently request == limits.
> feat: add support for resource limits

- common/src/peer_info.rs
- operator/src/network/controller.rs
- operator/src/network/mod.rs
- operator/src/network/peers.rs
- operator/src/network/stub.rs
- operator/src/network/testdata/bootstrap_job_cas_ipfs
- operator/src/network/utils.rs
- operator/src/simulation/controller.rs
- operator/src/utils/mod.rs
- runner/src/bootstrap.rs
- runner/src/simulate.rs
- runner/src/utils.rs
With this change the keramik-peers config map will contain both ceramic peers as well as generic IPFS peers.
The bootstrap methods have been updated accordingly.
#34 should merge first.
> feat: add bootstrap for cas-ipfs node

- operator/src/network/controller.rs
- operator/src/network/stub.rs
- operator/src/simulation/controller.rs
- operator/src/utils/test.rs
- runner/src/simulate.rs
Prior to this change the cas-ipfs peer info would be added to the network status with each call to reconcile. Additionally the simulation logic did not correctly ignore non Ceramic peers.
> fix: stop adding cas-ipfs status with each reconcile

- operator/src/network/ceramic.rs
- operator/src/network/testdata/default_stubs/ceramic_service
One of those "I'm not sure how it's working on kind and AWS" issues.
Problem:
DNS records for pods in a statefulset with attached service are not generated on GKE. They are on kind and EKS.
Analysis:
According to the spec, they shouldn't be!?!  
Service with ClusterIP (current config). 
https://github.com/kubernetes/dns/blob/master/docs/specification.md#23---records-for-a-service-with-clusterip 
[headless service](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services)
https://github.com/kubernetes/dns/blob/master/docs/specification.md#24---records-for-a-headless-service 
This PR makes the `ceramic` service headless, which means there is no proxying though a ClusterIP to a single address. All addresses will be returned.
``` …
```
> fix: ceramic service should be headless for pod dns

- operator/src/network/controller.rs
- operator/src/network/datadog.rs
Added ENV var to gather nodejs runtime info
Deployed to `ipfs-ceramic-service-headless` cluster
> fix: added DD_RUNTIME_METRICS_ENABLED to injected DD envs

- k8s/tests/check-network.sh
- k8s/tests/manifests/tests.yaml
There were two bugs in check-network:
1. If CAS was configured it would not detect the network is ready because there would be more peers in peers.json than expect. Keramik already accounts for this in its replicas and readyReplicas counts. So the script has been changed to only check the status counts instead of counting peers itself.
2. If CAS was configured it would emit an empty ComposeDB URL.
> fix: update check-network to handle CAS

- operator/src/network/mod.rs
A few of the new top level fields on the Network spec were using underscores. This fixes then to use camelCase.
> fix: add missing camelCase attribute

- Cargo.lock
- operator/Cargo.toml
- operator/src/network/ceramic.rs
- operator/src/network/mod.rs
This PR makes it possible to consume the keramik operator as a dependency in Rust code. Specifically we needed to update some deps (namely kube) and expose some types.
> chore: update deps and expose IPFS types

- operator/Cargo.toml
- operator/src/network/controller.rs
- operator/src/network/spec.rs
- operator/src/network/stub.rs
- operator/src/network/testdata/ceramics_weighted_status
- operator/src/network/testdata/delete_network
- operator/src/network/testdata/not_expired_status
- operator/src/simulation/controller.rs
- operator/src/utils/mod.rs
- operator/src/utils/test.rs
Now that we are programmatically creating networks (see ceramic-tests) we want to make sure we are not leaving lots of unused resources around.
With this feature the test driver can create networks with a generous TTL of a few hours (when we expect tests to run in a few minutes). If for some reason the test driver fails to clean up the network itself, eventually the operator will clean it up.
This feature remains optional so manually created networks are not affected.
> feat: add network TTL

- operator/src/network/cas.rs
- operator/src/network/controller.rs
- operator/src/network/testdata/default_stubs/cas_stateful_set
This PR adds an init container to run knex migrations before CAS services start.
Occasionally, the CAS API and worker will get stuck on the migrations table, which gets locked. Better to run the migrations ahead of time so that neither service needs to run them during startup.
> feat: run cas migrations in init container

- Dockerfile
Rust-builder no longer publishes the debian-latest tag and uses the debian flavor for its latest. This updates our Dockerfile to use the correct upstream parent image so we do not get glibc version conflicts.
> fix: update Dockerfile to use correct upstream parent

- operator/src/network/ceramic.rs
- operator/src/network/controller.rs
- operator/src/network/spec.rs
- operator/src/network/testdata/ceramic_ss_1
- operator/src/network/testdata/ceramic_ss_weighted_0
- operator/src/network/testdata/ceramic_ss_weighted_1
- operator/src/network/testdata/ceramic_ss_weighted_2
- operator/src/network/testdata/ceramic_ss_weighted_3
- operator/src/network/testdata/ceramic_ss_weighted_4
- operator/src/network/testdata/ceramic_ss_weighted_5
- operator/src/network/testdata/ceramic_ss_weighted_6
- operator/src/network/testdata/ceramic_ss_weighted_7
- operator/src/network/testdata/ceramic_ss_weighted_8
- operator/src/network/testdata/ceramic_ss_weighted_9
- operator/src/network/testdata/default_stubs/ceramic_stateful_set
This change allows us to play with all of the `ceramic-one` config via the network spec.
> feat: add env overrides to rust ipfs spec

- operator/src/network/cas.rs
- operator/src/network/testdata/default_stubs/localstack_stateful_set
Newer images are trying to delete the store and crashing because k8s won't allow that. I'd rather not muck with localstack settings to figure this out.
> fix: pin localstack image that doesn't try to delete its store

- operator/src/network/cas.rs
- operator/src/network/testdata/default_stubs/localstack_stateful_set
Built and pushed, seems to be working. There is data in the mapped path even with the pinned image version.
> fix: move persistant path for localstack to /var/lib

- keramik/src/SUMMARY.md
- keramik/src/advanced.md
- keramik/src/advanced_bootstrap.md
- operator/src/network/bootstrap.rs
- operator/src/network/ceramic.rs
- operator/src/network/controller.rs
- operator/src/network/spec.rs
Now its possible to simply disable the bootstrap process.
Additionally a small refactor was added to make the ceramic spec optional. Apparently k8s doesn't consider a vector optional and it must be explicit.
> feat: add enabled flag to bootstrap spec

- operator/src/network/cas.rs
- operator/src/network/testdata/default_stubs/localstack_stateful_set
v3 of the localstack-persist image isn't persisting sqs.
Switching to the older (2 weeks) v2 seems to work.
> fix: use localstack v2 for sqs persistence

- operator/src/network/cas.rs
- operator/src/network/controller.rs
- operator/src/network/testdata/default_stubs/cas_stateful_set
Upstream changed the env here https://github.com/ceramicnetwork/ceramic-anchor-service/pull/1177
> fix: env var changed for cas metrics

- .github/workflows/on-demand-build-images.yaml
The GCP route doesn't work with our Dockerfile mount cacheing (they have their own cacheing) so this seems easier.
> feat: Add workflow to build images on demand

- .github/workflows/on-demand-build-images.yaml
> fix: on-demand action image name fix

- Cargo.lock
- Makefile
- k8s/operator/manifests/operator.yaml
- keramik/src/advanced_configuration.md
- keramik/src/ipfs.md
- operator/src/network/cas.rs
- operator/src/network/ceramic.rs
- operator/src/network/controller.rs
- operator/src/network/ipfs.rs
- operator/src/network/mod.rs
- operator/src/network/spec.rs
- operator/src/network/testdata/ceramic_go_ss_1
- operator/src/network/testdata/ceramic_ss_1
- operator/src/network/testdata/ceramic_ss_weighted_0
- operator/src/network/testdata/ceramic_ss_weighted_1
- operator/src/network/testdata/ceramic_ss_weighted_2
- operator/src/network/testdata/ceramic_ss_weighted_3
- operator/src/network/testdata/ceramic_ss_weighted_4
- operator/src/network/testdata/ceramic_ss_weighted_5
- operator/src/network/testdata/ceramic_ss_weighted_6
- operator/src/network/testdata/ceramic_ss_weighted_7
- operator/src/network/testdata/ceramic_ss_weighted_8
- operator/src/network/testdata/ceramic_ss_weighted_9
- operator/src/network/testdata/default_stubs/cas_ipfs_stateful_set
- operator/src/network/testdata/default_stubs/ceramic_stateful_set
- operator/src/simulation/spec.rs
The changes to rust-ceramic that use the network to connect to a predefined set of nodes based on the network meant that the CAS ipfs node was connecting to clay and therefore the rest of the nodes would learn about and connect to clay.
This changes is so that CAS uses a shared IPFS spec with Ceramic, thus fixing the bug that the CAS ipfs network was not being configured.
This is a breaking change in that the pubsub_topic is no longer needed and the ipfs_resource_limits is removed from CAS as its not part of `ipfs` spec directly.
> fix: fixes bug where nodes were connecting to clay

- keramik/src/advanced_configuration.md
Description : 
Added documentation on how to enable recon with rust-ceramic. I have added how to do this under Advanced configurations in the documentation. 
Testing : 
Test Case : Check if the daemon is running with `recon` flag set to true, when a network is configured using the spec mentioned in advance configuration.
Output of logs : Recon flag is set to true in the daemon configurations
```
samikas@samikas-mbp keramik % kubectl logs ceramic-0-0 -c ipfs -n keramik-test-env
2024-01-05T18:26:41.799740Z  INFO ceramic_one: service__name: "ceramic-one", version: "0.9.0", build: "cargo:0.9.0", instance_id: "fallacious-representative", exe_hash: "uEiD9nHuu_MfKyTiRLNvR9MNhBhGTmj5klpZaY_aX99PpOQ"
at one/src/lib.rs:345
2024-01-05T18:26:41.876499Z DEBUG ceramic_one: using daemon options, opts: …
```
> docs: Added Documentation for enabling Recon with rust-ceramic

- runner/src/scenario/ceramic/model_reuse.rs
- runner/src/scenario/ceramic/new_streams.rs
- runner/src/scenario/ceramic/query.rs
- runner/src/scenario/ceramic/simple.rs
- runner/src/scenario/ceramic/write_only.rs
- runner/src/scenario/ipfs_block_fetch.rs
- runner/src/simulate.rs
This makes some changes to the runner to improve throughput and make the "users" key easier to understand and more likely to work.
- The `user` value in the spec is now defined as users/worker (node), rather than being the total users and needing to be divisible by the number of nodes.
- I removed the sleep between every transaction in a number of scenarios. As we're targeting one write/3.5 milliseconds, the current values aren't super insightful (way too lazy). The `SIMULATE_THROTTLE_REQUESTS` env var can be used to avoid each worker going bananas. If we want, we can expose the min/max wait as CLI options, as it can be applied to the scenario struct when building it.
- I added recording the ~~transaction, scenario, and~~ error logs on the goose workers as the scenario and transaction …
> feat: Remove transaction delays to improve throughput and change meaning of scenario runner users key

- Cargo.lock
- Cargo.toml
- common/src/peer_info.rs
- keramik/src/advanced_configuration.md
- keramik/src/simulation.md
- operator/src/network/ipfs_rpc.rs
- operator/src/simulation/controller.rs
- operator/src/simulation/manager.rs
- operator/src/simulation/spec.rs
- operator/src/simulation/worker.rs
- runner/Cargo.toml
- runner/src/bootstrap.rs
- runner/src/main.rs
- runner/src/scenario/ceramic/event_id_sync.rs
- runner/src/scenario/ceramic/mod.rs
- runner/src/scenario/ceramic/model_reuse.rs
- runner/src/scenario/ceramic/new_streams.rs
- runner/src/scenario/ceramic/query.rs
- runner/src/scenario/ceramic/recon_sync.rs
- runner/src/scenario/ceramic/simple.rs
- runner/src/scenario/ceramic/write_only.rs
- runner/src/scenario/ipfs_block_fetch.rs
- runner/src/simulate.rs
Linear ticket WS1-1409.
This PR includes #127 and pulls those changes into main, as well as some refactoring, and the implementation of two new scenarios called `recon-event-key-sync` and `recon-event-sync`. These scenarios include a step to inspect the goose metrics, as well as metrics from other peers to verify that the scenario passed. It will return a non-zero exit code if fails. This looks different to the manager process than an execution error, however, I'm not sure what needs to be done to prevent the manager from restarting in this case. As soon as it completes with the error, a new job starts but it won't actually start a new simulation (I hope/think this is okay).
The simulation spec includes a new field `success_request_target` that will control the threshold used to verify …
> feat: Add Recon event sync scenarios

- keramik/src/advanced_configuration.md
- keramik/src/simulation.md
- operator/src/monitoring/jaeger.rs
- operator/src/monitoring/opentelemetry.rs
- operator/src/monitoring/prometheus.rs
- operator/src/network/cas.rs
- operator/src/network/ceramic.rs
- operator/src/network/controller.rs
- operator/src/network/ipfs.rs
- operator/src/network/resource_limits.rs
- operator/src/network/spec.rs
- operator/src/simulation/controller.rs
- operator/src/simulation/redis.rs
- operator/src/simulation/spec.rs
I added a `devMode` boolean to the network and simulation specs, which will set all container resource requests/limits to None for CPU/RAM, unless explicitly included in the spec. Storage remains specified as a missing value is an error (it's possible I just missed the way around this, but it seems okay as it's not the issue). The network and simulation values are independent, network applies to those containers (e.g. CAS, IPFS) while the simulation applies to redis and the monitoring containers. 
I implemented it using a global variable for the network side, which is ugly. It applies to the entire system, and could mean other things in the future so it doesn't seem totally wrong, but it does seem wrong. I considered passing the spec down, or adding a new bool parameter but it will …
> feat: implement `devMode` setting to override all container resource requests/limits

- .gitignore
- local-scripts/load.py
- local-scripts/setup.sh
- local-scripts/small.yaml
I found myself nuking and re-creating my cluster _a lot_. Without a script like this, it takes forever to re-download all the images and get the cluster reconciled. This makes it much faster. You can just run `kind delete cluster && ./local-scripts/setup.sh "network.yaml"` and it will go through the steps of creating the cluster, applying the network and CRDs and then loading the images. 
It isn't one size fits all, but it does seem like a useful thing to include. If others disagree, I'm okay with closing this PR. I have a local version of .gitignore with my own folders commented with things like results, network and simulation definitions, and helper scripts. Also open to updating docs/readme etc to make the usage of these more obvious, but they're pretty straightforward scripts.
> feat: add scripts to help spin up local cluster

- Cargo.lock
- Cargo.toml
- common/Cargo.toml
- common/src/telemetry.rs
- k8s/operator/manifests/operator.yaml
- operator/src/main.rs
- operator/src/network/controller.rs
- operator/src/simulation/controller.rs
- runner/src/main.rs
- runner/src/simulate.rs
Now the operator exposes a prometheus scrape endpoint. It does not try to push its metrics over OTLP. This operator is long lived so this should not be a problem.
The runner continues to push its metrics over OTLP which is important since it is short lived.
However I was not able to get both prometheus scrape and OTLP push working on the same process. So the operator only supports prometheus and the runner only support OTLP push.
> feat: expose prometheus metrics from operator

- k8s/operator/manifests/podmonitor.yaml
Adds a podmonitor CRD to capture keramik operator metrics.
Deployments would add this resource to their kustomization.yaml to enable.
> feat: add podmonitor crd for keramik operator deployments

- runner/src/simulate.rs
Adjusts metric used for event sync success criteria based on [the rename](https://github.com/ceramicnetwork/rust-ceramic/pull/266) in rust ceramic
> fix: use new recon key metric name

- operator/src/network/controller.rs
- operator/src/network/ipfs_rpc.rs
CAS IPFS status lookup for durable networks pointing to external CAS is causing peer status reconciliation to fail.
I've only tested this on the Clay/Prod cluster so far, but their tests are now green!
https://github.com/3box/ceramic-tests/actions/runs/7848110468
https://github.com/3box/ceramic-tests/actions/runs/7848846872
> fix: add n/w check for cas ipfs during peer status updates

- operator/src/network/controller.rs
When reviewing the #144 I noticed a small optimization we can apply to the logic. Instead of collecting the peers into a vector and then using the length of the vector we can simply count the iterator directly, thus avoiding the allocations of the vector. Not that this code is perf sensitive but generally improves the readability of the code as its intention is clear.
> refactor: small change to only count connected peers

- operator/src/network/bootstrap.rs
- operator/src/network/cas.rs
- operator/src/network/ceramic.rs
- operator/src/network/controller.rs
- operator/src/network/mod.rs
- operator/src/network/node_affinity.rs
- operator/src/network/spec.rs
When node_selector_terms is set on a network all pods in the network will use those terms in order to control on which nodes the networks pods are scheduled.
This does not affect pods in simulations. I can add that if its needed/wanted.
> feat: adds node-affinity spec config

- runner/src/scenario/ceramic/recon_sync.rs
Use interests endpoint instead of deprecated subscribe endpoint for recon simulation.
> chore: use interests instead of subscribe recon endpoint in simulation

- Cargo.lock
- Cargo.toml
- common/src/telemetry.rs
- k8s/operator/manifests/operator.yaml
- operator/Cargo.toml
- operator/src/main.rs
- runner/Cargo.toml
- runner/src/main.rs
The operator no longer has a default opentelemetry endpoint and will only collect and send traces if an endpoint is configured.
This might address the memory leak but either way its a nice quality of life improvement as we have not been collecting traces from the operator anyway.
> fix: no default otel endpoint for the operator

- runner/src/simulate.rs
I calculated the value but didn't return it so that it was exported to grafana. That has been remedied.
> fix: expose min_peer_rps metric from CeramicNewStreamsBenchmark 

- operator/src/simulation/manager.rs
- operator/src/simulation/testdata/default_stubs/manager_job
When checking out the ephemeral usage on ipfs containers during simulation runs, it only occurs on tests that fail to reach the desired rps. We currently fail the job on this condition which causes the simulation-manager to restart.
This restart is unhandled by the scenario and causes worker restarts which appear to impact the ephemeral usage, as we're only seeing it on failed tests, after the scenario completes.
This PR addresses the situation by not restarting a failed simulation-manager job. While not ideal, it's a faster fix than coordinating the manager and workers after a failed job, as it could fail for reasons other than missing the desired rps.
> fix: dont restart simulation manager

- runner/src/scenario/ceramic/new_streams.rs
- runner/src/simulate.rs
We capture all peers average RPS over the simulation in `simulation_peer_requests_per_second` with an attribute of `peer`. We still have `simulation_min_peer_requests_per_second`. The motivation is being able to identify if changing something increases node writes, but reduces recon sync. We want a more clear picture of total writes in the scenario.
example includes the `ceramic-new-streams-benchmark` and `recon-event-sync` scenarios:
> feat: record all peer rps in grafana for simulations to calculate avg/min/max 

- operator/src/network/ceramic.rs
- operator/src/network/controller.rs
- operator/src/network/ipfs.rs
- operator/src/network/mod.rs
- operator/src/network/spec.rs
This creates a new debug mode flag on the network spec that enables security contexts and tokio console as appropriate.
This will require we redeploy the crds to the clusters but is a backwards compatible change.
> feat: add debug mode to network

- operator/src/simulation/controller.rs
- operator/src/simulation/manager.rs
- operator/src/simulation/spec.rs
- runner/src/simulate.rs
Don't write goose log files on workers unless requested. This will write goose logs to the manager stdout as well at the desired level. The simulation spec has a new field `logLevel: warn/info/debug/trace` and defaults to None (meaning off) if not set. This is a change, but these files haven't been generally useful afaik and it seems to consume a lot of RAM as they don't appear to be flushed until the end of the run. 
This requires redeploying the CRDs and the operator and runner images.
> chore: disable goose logs by default

- keramik/src/simulation.md
- runner/src/scenario/ceramic/mod.rs
- runner/src/scenario/mod.rs
- runner/src/scenario/recon_sync.rs
- runner/src/simulate.rs
We keep getting failures during longer simulations because the manager and workers disconnect at some point, and no metrics are reported by goose, however the prometheus metrics demonstrate that we would have still passed. Now we rely on goose for time, but keep a backup (this will be slightly longer and therefore won't bias us toward a better result), and use the prom metrics exclusively.
I also deleted the old recon keys only scenario as it no longer applies and is just noise.
Results from a 3 minute local test:
> chore: Less flaky results from scenario validation

- k8s/operator/manifests/operator.yaml
- keramik/src/monitoring.md
- operator/src/network/controller.rs
- operator/src/network/spec.rs
- operator/src/network/stub.rs
- operator/src/network/testdata/pod_monitor_get_ceramic
- operator/src/network/testdata/pod_monitor_get_ceramic_one
- operator/src/network/testdata/pod_monitor_get_crd
- operator/src/network/testdata/pod_monitor_get_otel
- operator/src/network/testdata/pod_monitor_post_ceramic
- operator/src/network/testdata/pod_monitor_post_ceramic_one
- operator/src/network/testdata/pod_monitor_post_otel
This PR adds automated creation of pod monitoring custom resources that can be used by the Grafana Cloud Agent for Keramik networks.
> feat: pod monitoring

- keramik/src/advanced_configuration.md
- operator/src/network/cas.rs
- operator/src/network/ceramic.rs
- operator/src/network/controller.rs
- operator/src/network/ipfs.rs
- operator/src/network/spec.rs
- operator/src/network/testdata/ceramic_ss_1
- operator/src/network/testdata/ceramic_ss_weighted_0
- operator/src/network/testdata/ceramic_ss_weighted_1
- operator/src/network/testdata/ceramic_ss_weighted_2
- operator/src/network/testdata/ceramic_ss_weighted_3
- operator/src/network/testdata/ceramic_ss_weighted_4
- operator/src/network/testdata/ceramic_ss_weighted_5
- operator/src/network/testdata/ceramic_ss_weighted_6
- operator/src/network/testdata/ceramic_ss_weighted_7
- operator/src/network/testdata/ceramic_ss_weighted_8
- operator/src/network/testdata/ceramic_ss_weighted_9
- operator/src/network/testdata/default_stubs/cas_ipfs_stateful_set
- operator/src/network/testdata/default_stubs/ceramic_stateful_set
- operator/src/utils/mod.rs
I moved the env overriding logic to a utility function, and included the sorting in there as well. This caused a lot of the test files to churn, but hopefully this will make them more consistent going forward.
> feat: allow overriding cas api envars

- operator/src/network/controller.rs
- operator/src/network/stub.rs
- runner/src/scenario/ceramic/models.rs
Currently getting u\0000 codepoints in the data, that crashes the postgres indexer because it's not allowed in jsonb data.
> chore: skip u\0000 when generating model random data

- Cargo.lock
- runner/src/scenario/ceramic/anchor.rs
- runner/src/scenario/ceramic/model_instance.rs
This updates the [rust-ceramic](https://github.com/ceramicnetwork/rust-ceramic/pull/351) and [ceramic http client](https://github.com/3box/ceramic-http-client-rs/pull/17) dependencies.
> chore: update http client

- operator/src/network/controller.rs
- operator/src/network/ipfs.rs
- operator/src/network/testdata/ceramic_ss_1
- operator/src/network/testdata/ceramic_ss_weighted_0
- operator/src/network/testdata/ceramic_ss_weighted_1
- operator/src/network/testdata/ceramic_ss_weighted_2
- operator/src/network/testdata/ceramic_ss_weighted_3
- operator/src/network/testdata/ceramic_ss_weighted_4
- operator/src/network/testdata/ceramic_ss_weighted_5
- operator/src/network/testdata/ceramic_ss_weighted_6
- operator/src/network/testdata/ceramic_ss_weighted_7
- operator/src/network/testdata/ceramic_ss_weighted_8
- operator/src/network/testdata/ceramic_ss_weighted_9
- operator/src/network/testdata/default_stubs/cas_ipfs_stateful_set
- operator/src/network/testdata/default_stubs/ceramic_stateful_set
As we know having less than 1 cpu can cause the odd deadlock in the C1 process. This makes the default a sane default.
> fix: update default resources for rust ipfs

- operator/src/network/cas.rs
- operator/src/network/controller.rs
- operator/src/network/testdata/default_stubs/cas_stateful_set
- operator/src/network/testdata/default_stubs/localstack_stateful_set
The CAS Scheduler specifies a location constraint when creating a S3 bucket. `us-east-1` is not a valid option when specifying the region.
> fix: use different aws region for cas than us-east-1

- keramik/src/advanced_configuration.md
- operator/src/network/cas.rs
- operator/src/network/ceramic.rs
- operator/src/network/controller.rs
- operator/src/network/ipfs.rs
- operator/src/network/mod.rs
- operator/src/network/spec.rs
- operator/src/network/storage.rs
Add persistent storage config object that allows modifying the persistent volume storage size and class. I updated a handful of tests to set this, so we see the 10 -> override value, demonstrating that the default is still 10 (and shown in tests that haven't been updated). If preferable, I can write dedicated tests for this new setting.
For IPFS, we allowed specifying `storageClass` before. We still support this field, but will prefer the `storage.class` field if it is set. If not, we will use `storageClass` (there are existing tests that demonstrate this).
> feat: support configuring persistent storage for containers

- operator/src/network/ceramic.rs
- operator/src/network/testdata/ceramic_go_ss_1
- operator/src/network/testdata/ceramic_ss_1
- operator/src/network/testdata/ceramic_ss_weighted_0
- operator/src/network/testdata/ceramic_ss_weighted_1
- operator/src/network/testdata/ceramic_ss_weighted_2
- operator/src/network/testdata/ceramic_ss_weighted_3
- operator/src/network/testdata/ceramic_ss_weighted_4
- operator/src/network/testdata/ceramic_ss_weighted_5
- operator/src/network/testdata/ceramic_ss_weighted_6
- operator/src/network/testdata/ceramic_ss_weighted_7
- operator/src/network/testdata/ceramic_ss_weighted_8
- operator/src/network/testdata/ceramic_ss_weighted_9
- operator/src/network/testdata/default_stubs/ceramic_stateful_set
- lower initial_delay_seconds so that healthchecks are run faster and pods are marked up earlier
- lower period_seconds so that there are less healthchecks (already enough load on the system!)
- increase timeout_seconds as the js-ceramic health check makes its own external calls to "ipfs" which where longer than this setting
> chore: update js-ceramic healthcheck timing

- Cargo.lock
- runner/Cargo.toml
- runner/src/scenario/ceramic/new_streams.rs
- runner/src/simulate.rs
Check the parent for description : https://github.com/3box/keramik/pull/184
> feat: aes-135-define-a-network-where-we-only-write-to-one-node-and-read

- runner/src/simulate.rs
Update metric to match renames in [rust ceramic](https://github.com/ceramicnetwork/rust-ceramic/pull/373). We fall back to old one if new doesn't exist so it should pass in CI/tests for either version of c1.
> chore: use new ceramic one metric for validation

- keramik/src/simulation.md
Updates the docs to include scenarios added and inclides instructions on how to run them
Scenarios : 
1) ceramic-anchoring-benchmark : This is the e2e test which creates models and passes when sync on the network is working and all streams have been anchored. We should set the CAS Api url in the network with proper dids to test against the CAS. 
```
casApiUrl: https://cas-dev-direct.3boxlabs.com
networkType: dev-unstable
privateKeySecret: ceramic-v4-dev
```
New Simulation vars for ceramic-anchoring-benchmark : 
` anchorWaitTime : Wait time in seconds for how long we want to wait after streams have been created to check when they have been anchored. This should be a high number like 30-40 minutes.`
2) cas-benchmark : This tests the write CAS load directly by passing c1 nodes. New …
> chore: update docs to include simulation specs

- operator/src/network/cas.rs
- operator/src/network/controller.rs
- operator/src/network/testdata/default_stubs/cas_stateful_set
- operator/src/network/testdata/default_stubs/ganache_stateful_set
When keramik is used to deploy CAS it is only in the context of a hermetic testing env. Therefore we can assume that anchoring should be as fast as possible in order to all for faster tests etc.
Makes two changes:
1. Reduces worker delay to 1s instead of 1m after completing a batch.
2. Configures ganache to instantly mine any transaction.
> feat: make anchoring fast by default

- operator/src/network/cas.rs
- operator/src/network/testdata/default_stubs/ganache_stateful_set
Using the instamine option of ganache confuses the CAS worker and it waits forever to see the transaction has been mined. This change uses a block time of 1 second, however in practice this appears to mean a block every 15 seconds. Faster than once a minute but still not very fast.
> fix: use smallest time for block time

- Cargo.lock
- runner/Cargo.toml
- runner/src/scenario/ceramic/anchor.rs
- runner/src/scenario/ceramic/mod.rs
- runner/src/scenario/ceramic/model_instance.rs
- runner/src/scenario/recon_sync.rs
- runner/src/scenario/util.rs
Updates the `ceramic-http-client-rs` dependency and uses the new event format from rust ceramic. This allows the `recon-event-sync` scenario to work without failing due "unexpected fields" when the API roundtrips the payload to make sure it is as expected.
> chore: update ceramic http client and fix recon sync test

- operator/src/network/ipfs.rs
- operator/src/network/testdata/go_ipfs_configmap
- operator/src/network/testdata/go_ipfs_configmap_1
- operator/src/network/testdata/go_ipfs_configmap_commands
We need to override the kubo API port at start up to match the port we're opening on the container.
> fix: set kubo API port to 5101

- operator/src/network/cas.rs
- operator/src/network/controller.rs
- operator/src/network/testdata/default_stubs/cas_stateful_set
The code for CAS API clustering (launching as many NodeJS processes as their are CPUs available) is not working in Keramik. This is causing the host's CPUs to be used, which launches 32 processes and causes the container to OOM.
This PR converts the CAS resource limits to an equivalent number of CPUs with a minimum of 1, and passes this number in to the container explicitly.
> fix: pass cas api cpus explicitly to the process

- operator/src/network/cas.rs
- operator/src/network/controller.rs
- operator/src/network/testdata/default_stubs/cas_stateful_set
Need CAS API changes currently in develop, but also probably a good idea to use the develop image in general.
> fix: use cas develop image by default

- local-scripts/load.py
- operator/src/network/ceramic.rs
- operator/src/network/controller.rs
- operator/src/network/testdata/ceramic_go_ss_1
- operator/src/network/testdata/ceramic_ss_1
- operator/src/network/testdata/ceramic_ss_weighted_0
- operator/src/network/testdata/ceramic_ss_weighted_1
- operator/src/network/testdata/ceramic_ss_weighted_2
- operator/src/network/testdata/ceramic_ss_weighted_3
- operator/src/network/testdata/ceramic_ss_weighted_4
- operator/src/network/testdata/ceramic_ss_weighted_5
- operator/src/network/testdata/ceramic_ss_weighted_6
- operator/src/network/testdata/ceramic_ss_weighted_7
- operator/src/network/testdata/ceramic_ss_weighted_8
- operator/src/network/testdata/ceramic_ss_weighted_9
- operator/src/network/testdata/default_stubs/ceramic_stateful_set
This aligns all the default versions of the software we set up in Keramik: `ceramic-one:latest` / `js-ceramic:develop` / `composedb:develop` / `ceramic-anchor-service:develop`.
Our tests will usually specify explicit versions of the software being tested.
Thanks for bringing this up, @samika98.
> fix: use composedb develop image by default

- Cargo.lock
- k8s/operator/manifests/operator.yaml
- operator/src/crdgen.rs
- operator/src/lgen/controller.rs
- operator/src/lgen/job.rs
- operator/src/lgen/mod.rs
- operator/src/lgen/spec.rs
- operator/src/lib.rs
- operator/src/main.rs
- operator/src/simulation/controller.rs
- runner/src/main.rs
Features in this pr : 
1) Generate crds with vars specific to load generation
2) Add reconciliation controller for load generation specific resources
3) Change operator yaml to give custom api access for generation load generation specific crds
Tests : 
Test 1 : Create a load generation and apply it. 
1.  Create a network (similar to basic.yaml) in the docs - network.yaml
2.  Create load generation yaml for configuring load generation 
```
apiVersion: "keramik.3box.io/v1alpha1"
kind: LoadGenerator
metadata:
name: load-gen
namespace: keramik-small
spec:
scenario: "model-load-sync"
runTime: 1
image: "samika98/runner:final-1"
imagePullPolicy: "IfNotPresent"
throttleRequests: 100
tasks: 10
```
Result : Success - Was able to generate load successfully against a ceramic node. Model got indexed …
> feat: lgen operator

- Cargo.lock
- Makefile
- k8s/operator/manifests/operator.yaml
- keramik/src/developing_runner.md
- keramik/src/load_generator.md
- operator/src/crdgen.rs
- operator/src/lgen/controller.rs
- operator/src/lgen/job.rs
- operator/src/lgen/mod.rs
- operator/src/lgen/spec.rs
- operator/src/lib.rs
- operator/src/main.rs
- operator/src/simulation/controller.rs
- runner/src/bootstrap.rs
- runner/src/load_generator/gen.rs
- runner/src/load_generator/mod.rs
- runner/src/load_generator/utils/ceramic_models_utils.rs
- runner/src/load_generator/utils/generator_utils.rs
- runner/src/load_generator/utils/mod.rs
- runner/src/main.rs
- runner/src/scenario/ceramic/mod.rs
- runner/src/simulate.rs
This PR introduces the initial logic for the runner. It includes the following key features:
- Adds a new command to the runner.
- Implements functionality to generate load against Ceramic instances.
This PR does not introduce any functional changes. It primarily adds interfaces and structures that will be used in future work. Once the operator changes are made, we will be able to call this command effectively.
This PR is part of a larger effort and contains several TODOs that will be addressed in subsequent PRs. 
For a quick review, the focus is on the runner logic and the new command implementation, rust coding practices/improvements.
> feat: add generator code
